homebrew_taps: []

homebrew_package_removals: []

homebrew_packages:
- aspell
- autojump
- autossh
- bash
- cabextract
- coreutils
- ffmpeg
- fzf
- git
- graphviz
- htop
- jq
- jsonlint
- libomp
- lsyncd
- mdcat
- mosh
- ripgrep
- rsync
- tmux
- tree
- wget
- youtube-dl
- imagemagick
- jpegoptim
- lesspipe
- libevent
- libpng
- libtool
- libyaml
- sqlite
- tree
- watch
- xz
- zlib
- zsh
- zsh-completions




homebrew_cask_packages:
- alfred
- anki
- disk-inventory-x
- dropbox
- docker
- font-roboto-mono
- font-ubuntumono-nerd-font
- franz
- google-chrome
- inkscape
- iterm2
- java
- karabiner-elements
- keyboard-maestro
- mactex
- skype
- rectangle
- vlc
- amazon-photos
- emacs-plus
- clipy
- spotify
- notion
- 1password
- slack
- flux
