- name: dotfiles dirs
  file:
    path: '~/.{{ item }}'
    state: directory
  loop:
  - ipython
  - ipython/profile_default
  - ipython/profile_default/startup
  - config
  - config/karabiner

- name: dotfiles files
  file:
    src: '{{ ansible_env.PWD }}/roles/macsetup/files/dotfiles/{{ item }}'
    path: '~/.{{ item }}'
    state: link
  loop:
  - config/karabiner/karabiner.json
  - config/yamllint/config
  - gitconfig
  - gitignore_global
  - ssh/config
  - ansible.cfg
  - ipython/profile_default/startup/00-imports.py
  - bashrc
  - profile
  - zshrc
